### ISSUE TITLE
Separate package for cli and package `sevm` to prevent unintended subdependencies

### ISSUE THREAD

**Issue by MbBrainz** [acuarica/evm#147]
Currently when you install sevm in your package, itll add the `ansi-colors`, `yargs` and `env-paths`  dependencies to your lock file. This is not intentional if you are only trying to use the package and not the cli. To reduce bundle size and keep the dependency tree clean, this should be separated.

**Comment by MbBrainz** [comment]
If Anyone sees this as well and wants to have a quick workaround: 
If you use `pnpm` as a package manager, You can force pnpm to [not install certain subdependencies](https://arc.net/l/quote/wvxbfphm) by adding the following overrides  to your root `package.json`: 
```json
{
"pnpm": {
   "overrides": {
      "...[other_overrides]",
      "sevm>ansi-colors": "-",
      "sevm>yargs": "-",
      "sevm>env-paths": "-"
   }
}}

**Comment by acuarica** [comment]
Hi @MbBrainz, thanks for sending this.

> To reduce bundle size _[..]_

Please keep in mind that it won't affect the bundle size. Those dependencies (and `js-sha3` as well) are only used by the CLI, so when you bundle the package, your bundler shouldn't include those dependencies. Moreover, the package should not depend on any Node specific API, meaning it should work in a browser without problem.

> _[..]_ and keep the dependency tree clean, this should be separated.

I understand this can be odd when wanting only the package. In fact, in the past I tried to keep the CLI dependencies to a minimum. However, I'm reluctant to split the package and the CLI (at least for now) if the only issue is the dependency tree.

**Comment by acuarica** [comment]
Hey @MbBrainz, going to close this for now. If it still represents a problem for you, feel free to reopen.

**Comment by MbBrainz** [comment]
@acuarica Thanks for the detailed explanation. I see indeed that in our build, those packages dont show up.
