### ISSUE TITLE
OOM for huge bytecodes

### ISSUE THREAD

**Issue by egorvas** [acuarica/evm#89]
Hi, I found that when I using your tool for large bytecodes (fox example like for this address 0x6bd332faf55d7b60096332b3fba3f84b8f601202) it cause error "FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory"
I tried to increase memory to 16 gb, but its didn help me.
With old implementation of the evm module it works fine.
Thanks for any help.

**Comment by acuarica** [comment]
Hi, thanks for sending this. Could you please provide the `sevm` version where it worked? With this it's easier to find where the problem was introduced.

**Comment by egorvas** [comment]
Sorry, apparently I expressed myself incorrectly. I mean that parsing (for bytecode of this address) works correctly with the original `evm` module (https://www.npmjs.com/package/evm)

**Comment by acuarica** [comment]
Hi @egorvas, this issue is fixed #94. It is included in the latest release https://github.com/acuarica/evm/releases/tag/v0.6.14. Give it a try!

**Comment by acuarica** [comment]
> I mean that parsing (for bytecode of this address) works correctly with the original evm module (https://www.npmjs.com/package/evm)

Just for reference, indeed, the original `evm` is able to parse the bytecode correctly. However, when trying to decompile it, `evm` raises the following error

```
Error: Stack too deep
```

**Comment by egorvas** [comment]
@acuarica thx, now its fine.
